---
# handlers file for ansible-role-pathvector

- name: reload bird
  ansible.builtin.systemd:
    name: bird
    state: reloaded
  when: not is_unifi_system | bool

- name: restart bird
  ansible.builtin.systemd:
    name: bird
    state: restarted
  when: not is_unifi_system | bool

- name: regenerate pathvector
  ansible.builtin.command: pathvector generate
  changed_when: true
  notify: reload bird
  when: not is_unifi_system | bool

- name: run unifi setup script
  ansible.builtin.command: "/data/on_boot.d/{{ pathvector_unifi_script_name | default('1-unifi-pathvector-setup.sh') }}"
  changed_when: true
  when: is_unifi_system | bool
