---
- name: Converge
  hosts: all
  become: true
  vars:
    playbook_dir: /root
    pathvector_skip_install: true
    pathvector_debug: true
    pathvector_run_script: false
    pathvector_config_path: /etc/pathvector.yml
    pathvector_deploy_only: false
  
  pre_tasks:
    - name: Create files directory
      ansible.builtin.file:
        path: /root/files
        state: directory
        mode: '0755'
    
    - name: Create test config file
      ansible.builtin.copy:
        dest: /root/files/instance.yml
        content: |
          asn: 65001
          router-id: 10.0.0.1
          source4: 10.0.0.1
          source6: fd00::1
          prefixes:
            - 10.0.0.0/24
  
  tasks:
    - name: Import pathvector role tasks
      ansible.builtin.import_tasks: ../../tasks/main.yml