---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  pre_tasks:
    - name: Create test configuration files
      delegate_to: localhost
      become: false
      block:
        - name: Ensure molecule ephemeral directory exists
          ansible.builtin.stat:
            path: "{{ molecule_ephemeral_directory | default('/tmp/molecule') }}"
          register: molecule_dir
          
        - name: Set playbook_dir fact
          ansible.builtin.set_fact:
            playbook_dir: "{{ molecule_ephemeral_directory | default('/tmp/molecule') }}/../.."
          run_once: true
        
        - name: Create files directory
          ansible.builtin.file:
            path: "{{ playbook_dir }}/files"
            state: directory
          run_once: true

        - name: Create test pathvector config for each host
          ansible.builtin.copy:
            dest: "{{ playbook_dir }}/files/{{ item }}.yml"
            content: |
              asn: 65001
              router-id: 10.0.0.1
              source4: 10.0.0.1
              source6: fd00::1

              prefixes:
                - 10.0.0.0/24
                - fd00::/48

              rtr-server: rtr.rpki.cloudflare.com:8282

              templates:
                upstream:
                  interpret-communities: true
                  filter-max-prefix: true
                  filter-rpki: true
                  filter-bogon-routes: true
                  filter-bogon-asns: true

              peers:
                test_peer:
                  asn: 65002
                  template: upstream
                  neighbors:
                    - 10.0.1.1
                    - fd00:1::1
          loop: "{{ groups['all'] }}"
          run_once: true

  tasks:
    - name: Import main tasks
      ansible.builtin.import_tasks: ../../tasks/main.yml

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: ../../handlers/main.yml