---
- name: Verify
  hosts: all
  become: true
  
  tasks:
    - name: Check if pathvector config was deployed
      ansible.builtin.stat:
        path: /etc/pathvector.yml
      register: config_check
    
    - name: Assert config exists
      ansible.builtin.assert:
        that:
          - config_check.stat.exists
        fail_msg: "Pathvector config was not deployed to /etc/pathvector.yml"
        success_msg: "Pathvector config successfully deployed"